### ISSUE TITLE
ModuleNotFoundError: No module named 'pyngp'

### ISSUE THREAD

**Issue by nyacg** [camenduru/instant-ngp-colab#1]
It seems the version of pyngp that is in the zip file is for python 3.8 

**pyngp**
```
Archive:  /content/instant-ngp.zip
   creating: instant-ngp/build/
  inflating: instant-ngp/build/instant-ngp  
  inflating: instant-ngp/build/pyngp.cpython-38-x86_64-linux-gnu.so  
```

**python**
```
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: commentjson in /usr/local/lib/python3.9/dist-packages (0.9.0)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.9/dist-packages (0.13.2)
```

Unfortunately adding `sys.path.append("/content/instant-ngp/build/pyngp.cpython-38-x86_64-linux-gnu.so")` to `run.py` (as per https://github.com/NVlabs/instant-ngp/issues/43) hasn't worked. I also can't actually see `pyngp.cpython-38-x86_64-linux-gnu.so` in the filesystem but this may just be because Colab hides it 🤷

**Comment by camenduru** [comment]
thanks for the info @nyacg ❤ please try again maybe works
