### ISSUE TITLE
missing in-repo zip files (ceres-solver-v2.zip & instant-ngp-v2.zip)

### ISSUE THREAD

**Issue by omriio** [camenduru/instant-ngp-colab#3]
Hi, thanks for your time sharing this repo.
When trying to run from colab notebook i'm getting 
```
--2023-10-01 08:27:47--  https://github.com/camenduru/instant-ngp-colab/releases/download/v1.0/instant-ngp-v2.zip

Resolving github.com (github.com)... 140.82.112.3

Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
...
--2023-10-01 08:27:45--  https://github.com/camenduru/instant-ngp-colab/releases/download/v1.0/ceres-solver-v2.zip

Resolving github.com (github.com)... 140.82.114.3

Connecting to github.com (github.com)|140.82.114.3|:443... connected.

HTTP request sent, awaiting response... 302 Found
```

could you please re-upload it or link to the correct download path?

**Comment by camenduru** [comment]
please check: https://github.com/camenduru/instant-ngp-colab/releases

**Comment by omriio** [comment]
thanks for the fast response!
after looking closely it does find it after the 302 error and download locally and unpack but still when running the scond cell i'm getting
`==== running: colmap feature_extractor --ImageReader.camera_model OPENCV --ImageReader.camera_params "" --SiftExtraction.estimate_affine_shape=true --SiftExtraction.domain_size_pooling=true --ImageReader.single_camera 1 --database_path colmap.db --image_path "/content/train"
colmap: error while loading shared libraries: libGLEW.so.2.1: cannot open shared object file: No such file or directory
FATAL: command failed

**Traceback (most recent call last):
  File "/content/instant-ngp/./scripts/run.py", line 25, in <module>
    import pyngp as ngp # noqa
ModuleNotFoundError: No module named 'pyngp'**`
